version: '3.8'

volumes:
  qdrant_data: /Users/abcom/Desktop/docker_volumes/qdrant
  meilisearch_data: /Users/abcom/Desktop/docker_volumes/meilisearch
  postgres_data: /Users/abcom/Desktop/docker_volumes/postgres_data

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_MASTER_KEY: 'aSampleMasterKey'
  llm-db:
    image: postgres:latest
    container_name: postgres-llm-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: llm_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
