version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /Users/abcom/Desktop/docker_volumes/qdrant:/qdrant/storage
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - /Users/abcom/Desktop/docker_volumes/meilisearch:/meili_data
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_MASTER_KEY: 'aSampleMasterKey'